services:
  telegraf:
    image: telegraf
    restart: unless-stopped
    user: 1013:995    # Change to whatever suits your needs
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./telegraf/telegraf.weather.conf:/etc/telegraf/telegraf.d/telegraf.weather.conf
    env_file:
      - telegraf-settings.env
