{
 "title": "Solaranlage Multi-Inverter",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "city_id", "label": "City used to get the weather", "query": "${VAR_CITY_ID}" },
   {
    "name": "location_longitude",
    "label": "Longitude of the location of your solar panels",
    "query": "${VAR_LOCATION_LONGITUDE}"
   },
   {
    "name": "location_latitude",
    "label": "Latitude of the location of your solar panels",
    "query": "${VAR_LOCATION_LATITUDE}"
   },
   { "name": "bucket_opendtu", "label": "Bucket OpenDTU data", "query": "${VAR_BUCKET_OPENDTU}" },
   { "name": "bucket_weather", "label": "Bucket for weather data", "query": "${VAR_BUCKET_WEATHER}" }
  ]
 },
 "panels": [
  { "title": "Übersicht", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Produktion Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket_opendtu}\")\n  |> range(start: 1)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"output_per_dtu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"yieldtotal\")\n  |> last()\n  |> group( columns: [] )\n  |> sum()\n"
    }
   ]
  },
  {
   "title": "Letzte 14 Tage",
   "type": "table",
   "gridPos": { "h": 16, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "query": "import \"timezone\"\noption location = timezone.location(name: \"Europe/Berlin\")\n\nfrom(bucket: \"${bucket_opendtu}\")\n  |> range(start: - 14d, stop: today())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"output_per_inverter\")\n  |> filter(fn: (r) => r[\"_field\"] == \"yieldday\")\n  |> aggregateWindow(every: 1d, fn: max, createEmpty: false)\n  |> timeShift(duration: -1s)\n  |> drop(columns: [\"_start\", \"_stop\", \"_field\", \"_measurement\", \"dtu\"])\n  "
    },
    {
     "query": "import \"timezone\"\r\noption location = timezone.location(name: \"Europe/Berlin\")\r\n\r\nfrom(bucket: \"${bucket_opendtu}\")\r\n  |> range(start: - 14d, stop: today())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"output_per_inverter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"yieldday\")\r\n  |> drop( columns: [\"dtu\"] )\r\n  |> aggregateWindow(every: 1d, fn: max, createEmpty: false)\r\n  |> timeShift(duration: -2h, columns: [\"_time\"])   // Compensate the time shift introduced by aggregateWindow  \r\n  |> group(columns: [\"_time\"])\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false, timeDst: \"agg_time\")\r\n  |> group(columns: [\"\"])  \r\n  |> drop(columns: [ \"_start\", \"_stop\", \"agg_time\"])\r\n  |> rename(columns: {_value: \"total\", _time: \"Time\"})"
    }
   ]
  },
  {
   "title": "Aktuelle Leistung AC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket_opendtu}\")\r\n  |> range(start: today(), stop: -10s)  // Last time bucket may not have all values\r\n  |> filter( fn: (r) => r[\"_measurement\"] == \"output_per_dtu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"power\")\r\n  |> aggregateWindow(every: 30s, fn: mean, createEmpty: false)\r\n |> group(columns: [\"_time\"])\r\n |> aggregateWindow(every: 10s, fn: sum, createEmpty: false, timeDst: \"agg_time\")\r\n |> group(columns: [\"\"])  \r\n |> drop(columns: [ \"_start\", \"_stop\", \"agg_time\"])"
    }
   ]
  },
  {
   "title": "Spitzenleistung Heute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket_opendtu}\")\r\n  |> range(start: today())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"output_per_dtu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"power\")\r\n  |> max()\r\n  |> group(columns: [])\r\n  |> sum()"
    }
   ]
  },
  {
   "title": "Produktion Heute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket_opendtu}\")\n  |> range(start: today())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"output_per_dtu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"yieldday\")\n  |> last()\n  |> group( columns: [] )\n  |> sum()"
    }
   ]
  },
  {
   "title": "Aktuelle Leistung AC",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket_opendtu}\")\n  |> range(start: today())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"output_per_inverter\")\n  |> filter(fn: (r) => r[\"_field\"] == \"power\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Spitzenleistung Heute",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket_opendtu}\")\n  |> range(start: today())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"output_per_inverter\")\n  |> filter(fn: (r) => r[\"_field\"] == \"power\")\n  |> max()\n"
    }
   ]
  },
  {
   "title": "Produktion Heute",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket_opendtu}\")\n  |> range(start: today())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"output_per_inverter\")\n  |> filter(fn: (r) => r[\"_field\"] == \"yieldday\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Produktion Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket_opendtu}\")\n  |> range(start: 1)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"output_per_inverter\")\n  |> filter(fn: (r) => r[\"_field\"] == \"yieldtotal\")\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Produktion Heute",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket_opendtu}\")\r\n  |> range(start: today())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"output_per_dtu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"yieldday\")\r\n  |> aggregateWindow(every: 30s, fn: mean, createEmpty: false)\r\n |> group(columns: [\"_time\"])\r\n |> aggregateWindow(every: 10s, fn: sum, createEmpty: false, timeDst: \"agg_time\")\r\n |> group(columns: [\"\"])  \r\n |> drop(columns: [ \"_start\", \"_stop\", \"agg_time\"])"
    }
   ]
  },
  { "title": "Verlauf", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "AC Seite",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket_opendtu}\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"output\")\n  |> filter(fn: (r) => r[\"_field\"] == \"current\"  )\n  |> last()"
    },
    {
     "query": "from(bucket: \"${bucket_opendtu}\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"output\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage\" )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Leistungsverlauf",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket_opendtu}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"output\")\n  |> filter(fn: (r) => r[\"_field\"] == \"power\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n\n\n"
    },
    { "latitude": "$location_latitude", "longitude": "$location_longitude", "target": [ "sun_altitude" ] },
    {
     "query": "from(bucket: \"${bucket_weather}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cloudiness\")\r\n  |> filter(fn: (r) => r[\"city_id\"] == \"$city_id\")\r\n  |> filter(fn: (r) => r[\"forecast\"] == \"*\")  \r\n  |> drop(columns: [\"condition_id\", \"condition_main\"])\r\n  |> sort(columns: [\"_time\"], desc: false)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"${bucket_opendtu}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"output_per_dtu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"power\")\r\n  |> aggregateWindow(every: 10s, fn: max, createEmpty: false)\r\n  |> group(columns: [\"_time\"], mode: \"by\")\r\n  |> sum(column: \"_value\")  \r\n  |> group()\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)  \r\n  |> yield(name: \"total\")"
    }
   ]
  },
  {
   "title": "Wechselrichter Temperatur",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket_opendtu}\")\n  |> range(start: - 5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"inverter\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> drop( columns:[\"dtu\", \"_field\"])\n  |> last()"
    }
   ]
  },
  {
   "title": "Sonnenaufgang",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\n  |> range(start: today())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sunrise\")\n  |> filter(fn: (r) => r[\"city_id\"] == \"${city_id}\")\n  |> map(fn: (r) => ({ r with _value: r._value / 1000000 })) // Millisekunden\n  |> last()\n\n\n"
    }
   ]
  },
  {
   "title": "DC Kanäle",
   "type": "timeseries",
   "description": "Strom und Spannung der einzelnen Kanäle über die Zeit",
   "gridPos": { "h": 19, "w": 19, "x": 5, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket_opendtu}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"input\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current\")\r\n  |> drop(columns: [\"dtu\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"${bucket_opendtu}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"input\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage\")\r\n  |> drop(columns: [\"dtu\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> yield(name: \"mean\")"
    },
    { "latitude": "$location_latitude", "longitude": "$location_longitude", "target": [ "sun_altitude" ] }
   ]
  },
  {
   "title": "Sonnenuntergang",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather\")\n  |> range(start: today())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sunset\")\n  |> filter(fn: (r) => r[\"city_id\"] == \"${city_id}\")\n  |> map(fn: (r) => ({ r with _value: r._value / 1000000 })) // Millisekunden\n  |> last()\n\n\n"
    }
   ]
  },
  {
   "title": "DC Leistung Strings",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket_opendtu}\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"input\")\n  |> filter(fn: (r) => r[\"_field\"] == \"power\")\n  |> drop( columns: [\"dtu\"])\n  |> last()"
    }
   ]
  },
  {
   "title": "DC Leistung auf den Strings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket_opendtu}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"input\")\n  |> filter(fn: (r) => r[\"_field\"] == \"power\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    { "latitude": "$location_latitude", "longitude": "$location_longitude", "target": [ "sun_altitude" ] }
   ]
  }
 ]
}